### ISSUE TITLE
Determine architecture

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#105]
We should consider how our current architecture will best translate into a SPA.

One key point to determine is whether each Elm app in our overall application maps cleanly to an individual page or if some of the apps comprise multiple pages. In particular, we should think about the student and instructor apps. Do they draw common functionality from the same modules or do they have their own implementations?

A couple of architectures that we might consider include:

1. A unified application where students and instructors are presented different views and behaviors based on a type

2. Two sub-applications where students and instructors have their own implementations but draw from common modules where it makes possible 

For the first idea, the type might be something like

```
type User
    = Instructor Cred
    | Student Cred
    | Anonymous
```

If we determine that each app in the current application cleanly maps to an individual page, the unified application seems like a good approach. If not, we might consider the two sub-applications approach or determine the level of effort to move towards a unified application.

**Comment by andrew-silvernail** [comment]
This is interesting.  Let's talk about this today. I'm assuming option #1 would still draw from common modules, where appropriate.

**Comment by bgins** [comment]
Yep, that's right.
