### ISSUE TITLE
Local development and build

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#111]
We should consider using `parcel` for local development and for building the application. This would provide us with hot reloading and other local development benefits. We would also be able to use TypeScript for free if we want to.

The `parcel` build will give us a nice minified and optimized bundle that we can serve in production.

**Comment by andrew-silvernail** [comment]
Let's take out the quick-and-dirty minification happening on the backend after we've setup `parcel`.  I've created issue #113 for this.
