### ISSUE TITLE
Create a single page for the Elm application on the backend

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#114]
This would facilitate the rest of development towards an Elm SPA.

- The page should not require Django auth.
- Caching headers should encourage clients not to cache the JavaScript.
- Only HTTP GET should be allowed when fetching this page.

We can set this up via nginx.

**Comment by jdelamare** [comment]
Done, see [upgrade/proxy-ssl](https://github.com/ereadingtool/ereadingtool/tree/upgrade/proxy-ssl)
