### ISSUE TITLE
Elm SPA: Use JWTs for auth

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#117]
We should switch from using cookies for auth to use JWTs instead. The rationales for this change:

- JWTs have a well-defined method for signing and verifying tokens using asymmetric encryption
- JWTs are not sent automatically with each browser request which means they do not pose the CSRF risks associated with cookies

Let's find a JWT library that will work with Django. An approach to managing tokens in the frontend has been outlined in #107.

**Comment by andrew-silvernail** [comment]
Added JWT support to the backend in #118 .
