### ISSUE TITLE
Glossing issues

### ISSUE THREAD

**Issue by verbruggenh** [ereadingtool/ereadingtool#12]
On the instructor side, when I am trying to add or change a definition for a word, punctuation often will be added to the word, and then I can't add or change anything. The problems pop up with the following punctuation:

« » ( ) : / - (as in пресс-служба)

Also, I often won't be able to add or change a definition for the first word of a sentence.

**Comment by bgins** [comment]
The changes in #300 resolve both of the issues mentioned here.
