### ISSUE TITLE
Refactor Flashcard Elm modules to new namespace

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#127]
Elm modules in `flashcard/ui/` need to be moved to the new `web/src/` directory.  No renaming is required.

**Comment by bgins** [comment]
We have one page to add from `flashcards/ui/`: `Flashcards.elm`.

**Comment by bgins** [comment]
Flashcard modules have been refactored and an initial flashcards page has been implemented. See #182 for the remaining work on the flashcards page.
