### ISSUE TITLE
Add new Django endpoints for student and instructor profile data

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#148]
Note:

- Does not include endpoint URIs.

**Comment by bgins** [comment]
It looks like we might already have a student profile link that I overlooked:

https://github.com/ereadingtool/ereadingtool/blob/914dbd3d1e5748b84f4b6f4764608b2fedc167f4/user/urls/student.py#L13

I don't think we are using it now to retrieve profiles, but maybe this will return a student profile on a GET?

**Comment by andrew-silvernail** [comment]
> It looks like we might already have a student profile link that I overlooked:
> 
> https://github.com/ereadingtool/ereadingtool/blob/914dbd3d1e5748b84f4b6f4764608b2fedc167f4/user/urls/student.py#L13
> 
> I don't think we are using it now to retrieve profiles, but maybe this will return a student profile on a GET?

Let's see, so that endpoint currently returns a dictionary like:

```
{
            'id':: int,
            'username':: string,
            'email':: string,
            'difficulty_preference': [difficulty_slug::string, difficulty::string],
            'difficulties': [[text_difficulty_slug::string, text_difficulty_name::string], ...]
            'uris': {
                'logout_uri':: string,
                'profile_uri':: string
            }
}
```

on the web side this is our definition of student profile:

```
type StudentProfile
    = StudentProfile (Maybe Int) (Maybe StudentResource.StudentUsername) StudentResource.StudentEmail (Maybe Text.TextDifficulty) (List Text.TextDifficulty) StudentURIs
```

These seem to match up, so it looks like we can use this.  We can leave this ticket open in case we need to make changes to the endpoint.

**Comment by bgins** [comment]
This endpoint worked out as needed.
