### ISSUE TITLE
Add student profile page

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#149]
The following items should be checked off to complete the transition of the student profile page:

- [x] Page loads
- [x] Logout works
- [x] Navbar links route to the right pages
- [x] Retrieve and display a student's profile on init 
- [x] Show help messages to new students
- [x] Student can update their username
- [ ] ~~Flashcard words are displayed~~ (Moved to #182)
- [x] Student can set their preferred difficulty
- [x] Student can set or unset research consent preference
- [x] Performance report is displayed in the profile
- [x] Performance report can be downloaded as a PDF
- [x] Contact links work

**Comment by wcomer** [comment]
10/14 I logged into steps2ar.org for the first time and it remembered me (sort of...)
I didn't need to create a new user account, but my profile page is empty (my user name doesn't appear, nor does my email address appear). 
I can kinda change my username but it doesn't seem to store that changes when I make it.

**Comment by wcomer** [comment]
The styling of the box to select difficulty is missing and except for a down arrow in the middle of that section there's no hint about what level the user has selected.

**Comment by bgins** [comment]
The styling issues for the select difficulty box are fixed in #204.
