### ISSUE TITLE
Make trailing slash optional for API endpoints

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#153]
In all API addresses, remove the trailing slash.

**Comment by jdelamare** [comment]
Removing the forward slash in the string "username/" on [line 108 file Endpoint.elm](https://github.com/ereadingtool/ereadingtool/blob/7832055b4fa2bb3c6b61aa4e6f43cfe8adf46c34/web/src/Api/Endpoint.elm#L106-L108) will lead to Django automatically appending a slash. This is in an effort for it to maintain "beautiful" URLs. When `CommondMiddleware` is installed, as it is in this project, the `APPEND_SLASH` setting is defaulted to `True`. The downside of this is that the `POST` data may be dropped during the redirect to the new URL. You can see the redirect happen in the image below.
![Screen Shot 2020-09-11 at 2 51 36 PM](https://user-images.githubusercontent.com/32110740/92976689-fa704480-f43f-11ea-8d65-402a4e77d2f4.png)
Here is a screenshot of the documentation for completion's sake:
<img width="834" alt="Screen Shot 2020-09-11 at 2 51 50 PM" src="https://user-images.githubusercontent.com/32110740/92976716-0eb44180-f440-11ea-9a0e-b1612c1b56d3.png">

To fix this, I propose adding a second route without a slash that points to the same view.
![Screen Shot 2020-09-11 at 2 52 50 PM](https://user-images.githubusercontent.com/32110740/92977248-59828900-f441-11ea-941d-6e049725ccbc.png)

In practice, it seems to work. Further analysis of the documentation is needed.
![Screen Shot 2020-09-11 at 2 54 17 PM](https://user-images.githubusercontent.com/32110740/92977265-669f7800-f441-11ea-89b1-715a4e2bca01.png)

**Comment by bgins** [comment]
Looking through the URLs, it looks like we will want to allow the following endpoints to be accessible without the trailing slash:

 https://github.com/ereadingtool/ereadingtool/blob/7832055b4fa2bb3c6b61aa4e6f43cfe8adf46c34/ereadingtool/urls.py#L45

https://github.com/ereadingtool/ereadingtool/blob/7832055b4fa2bb3c6b61aa4e6f43cfe8adf46c34/user/urls/student.py#L9-L16

https://github.com/ereadingtool/ereadingtool/blob/7832055b4fa2bb3c6b61aa4e6f43cfe8adf46c34/user/urls/instructor.py#L8-L13

https://github.com/ereadingtool/ereadingtool/blob/7832055b4fa2bb3c6b61aa4e6f43cfe8adf46c34/user/urls/forgot_pass.py#L8-L11

There may be more including the websocket endpoints.

**Comment by jdelamare** [comment]
This has been addressed with a new ![branch](https://github.com/ereadingtool/ereadingtool/compare/upgrade/slashless_endpoints).

**Comment by bgins** [comment]
Made some changes to remove the trailing slashes from the frontend here: https://github.com/ereadingtool/ereadingtool/commit/97a7f588d7c805f0d7d92eb014fae729bc113f88

This works now for logging in and retrieving profiles, but we are missing a few and there are some with CSRF errors that are showing up now. The CSRF errors are on `api/username` and `api/student/<int:pk>/consent_to_research`.

The new ones I found are in

https://github.com/ereadingtool/ereadingtool/blob/97a7f588d7c805f0d7d92eb014fae729bc113f88/text/urls.py#L12-L42

presumably anything that starts with `api`. We aren't using many of these yet, but we are using this one to retrieve texts on text search:

https://github.com/ereadingtool/ereadingtool/blob/97a7f588d7c805f0d7d92eb014fae729bc113f88/text/urls.py#L32

**Comment by jdelamare** [comment]
This work continues on in [upgrade/slashless_endpoints](https://github.com/ereadingtool/ereadingtool/tree/upgrade/slashless_endpoints)

**Comment by jdelamare** [comment]
May need to drop the slash on the websocket endpoints.

https://github.com/ereadingtool/ereadingtool/blob/8fd9bbe6fb4bf6a43a92430ec70dff4b6cbb41de/ereadingtool/routing.py#L12-L23

**Comment by jdelamare** [comment]
The new `upgrade/jwt_auth` branch has removed the slashes from the end of the websocket endpoints.

**Comment by jdelamare** [comment]
This seems to have been entirely addressed with the PR that brought  `upgrade/jwt_auth` in.
