### ISSUE TITLE
Add text reader page

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#157]
The following items should be checked off to complete the transition of the student profile page:

- [x] Page loads
- [x] Logout works
- [x] Navbar links route to the right places
- [x] ~~Text title displayed as browser tab title~~ (Text ID displayed as browser tab title.)
- [x] Text loads over websocket on page init
- [x] Navigation through text works. This includes start, previous, next, and start over buttons
- [x] Text loads at the appropriate stage of progress
- [x] Modals for texts display and show gloss 
- [ ] ~~Modals provide an option to add or remove flashcards~~ (moved to #182)
- [x] Questions and answers display and progress responding to questions is tracked 
- [x] Text score is displayed when the text is complete

A few technical requirements:

- [x] A websocket implementation with websocket endpoints and a websocket module
- [x] Implement text sections and modals in a way that works in Elm 0.19. These currently use `HtmlParser` and `VirtualDom` and there may be some work to transition them over.
- [x] Investigate changes to `Regex` library and update our code to use it correctly. A few changes were made in caf74e5a8b4ecf7702aa728b1942514bb25f7131, but these have not been tested.
- [x] Look carefully at `web/src/Text/Section/Words/Tag.elm`. Many changes were made in caf74e5a8b4ecf7702aa728b1942514bb25f7131 to get things compiling and the changes might be wrong!

**Comment by wcomer** [comment]
Just popped into the development version of the site, and I worked through one text and then wanted to go back to it and re-read. That blew me away -- the URL turned to .../text/0 and I got an error message.

**Comment by wcomer** [comment]
When I select a text from the list, it seems to move me past the short preview and the "start button"
