### ISSUE TITLE
Genericize APIView to use CSRF exempt and use it everywhere

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#172]

**Comment by bgins** [comment]
A couple additional routes to be CSRF exempted that are failing on `upgrade/staging` related to profiles:

```
/api/username
/api/student/<id>
/api/student/<id>/consent_to_research
```

This one is not on `upgrade/staging` yet, but will be soon:
```
/api/text/<id>/lock
```

**Comment by jdelamare** [comment]
I'm going to close this issue for now. It may rear it's ugly head in the future though
