### ISSUE TITLE
Add flashcards

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#182]
The following items should be checked off to complete the transition of the flashcards page:

- [x] Page loads
- [x] Logout works
- [x] Navbar links route to the right places
- [ ] Student can select "Review" or "Review and Answer" mode
- [ ] "Review" mode shows student flashcards. Student can flip flahscards and move backwards and forwards through them.
- [ ] "Review and Answer" prompts the student to translate the word on each flashcard and asks them to rate difficulty.

Flashcards integrate with the text reader page:

- [ ] Modals that open when a word is highlighted provide an option to add or remove flashcards

Flashcards integrate with the student profile page:

- [ ] Flashcard words are displayed

The navbar provides a way to navigate to the Flashcards page:

- [ ] Navbar has a link to Flashcards page

**Comment by jdelamare** [comment]
There is a need to export a student's set of words they've chosen to study to a CSV file. From there it can be uploaded to a flashcard service like Quizlet.

**Comment by jdelamare** [comment]
We'll no longer show flashcards in their own page. Instead, we'll have students download their flashcards from their profile page.

**Comment by jdelamare** [comment]
PDF and CSV takes care of this flashcards => my words
