### ISSUE TITLE
Return 403 on API endpoints when JWT is invalid

### ISSUE THREAD

**Issue by jdelamare** [ereadingtool/ereadingtool#228]
Just about every API endpoint will need to return a 403 `{ error: "Token expired" }` if they're accessed with an invalid JWT. That being the case, it makes sense to make a decorator.

**Comment by jdelamare** [comment]
@bgins in the current implementation I look for the JWT as a query string parameter. Are we thinking it'll be appended to all requests? If so the decorator (decorator factory really) has been written. I'd like to smooth some stuff out so it can be applied to both the performance report endpoint and websocket endpoint. After that we should be good to get at least the decorator itself into `upgrade/staging`.

**Comment by bgins** [comment]
The JWT is only a query string parameter on the performance report endpoint and the websocket endpoint. In all other API requests it is on the `Authorization` header. Like

```
Authorization: Bearer <token>
```

**Comment by jdelamare** [comment]
Ahh of course. I'll be sure to dig into that.

**Comment by jdelamare** [comment]
Ok, the code certainly works. Now there is need to identify which endpoints actually need this check. The less obvious places surround the password reset functionality. Still unsure of what `uidb54` is supposed to represent. Holding off on this area for a bit. 

Also holding off on decorating the performance report since the logic is a bit different there. We're returning the student object to be validated against the `pk` in the caller. Currently unsure, might be able to use the decorator if we shuffle things around.

For now just decorating functions with `API` in their name.
