### ISSUE TITLE
Dead Code Elimination

### ISSUE THREAD

**Issue by jdelamare** [ereadingtool/ereadingtool#233]
There are a multitude of files which can be removed given the new shape of the app. If the code is mixed with other legitimate code than the lines are referred to below. If entire directories of code may deleted than just those directories are listed. We'll need to test to make sure the code isn't used in any way prior to its removal. Particularly for the pieces of code which have more opaque purpose than the directories which serve static files.

Directories:
- [x]  `ui/`
- [x] `ereadingtool/static/`
- [x] `ereadingtool/templates/`
- [x] `flashcards/static/`
- [x] `flashcards/templates`
- [x] `flashcards/ui/`
- [x] `instructor_admin/static/`
- [x] `instructor_admin/templates/`
- [x] `instructor_admin/ui/`
- [ ]  ~`report/templates/`~  Can't get rid of this because it's used to create student performance report PDF
- [x] `text/static/`
- [x] `text/templates/`
- [x] `text/ui/`
- [x] `user/static/`
- [x] `user/templates/`
- [x] `user/ui/`

Code:

**Comment by bgins** [comment]
Let's see if we can resolve #113 when we do this.

**Comment by bgins** [comment]
Before deleting, all files in the `static` directories should be in `web/public/` with the exception of

- `flashcards/static/js/websockets.js`
- all files in `instructor_admin/static/admin/js/ckeditor/`
