### ISSUE TITLE
Deleting accounts

### ISSUE THREAD

**Issue by verbruggenh** [ereadingtool/ereadingtool#27]
The same person from #26 is having issues creating a student account. I think she means that she is trying to create new accounts with already used email addresses, since she has forgotten the passwords. If the following email addresses have accounts tied to them, could you please delete the accounts? Also, if you delete the accounts, will she be able to create fresh accounts with the same email addresses?

kresin@ad.ucla.edu
kresin@ucla.edu
Russianflagship@international.ucla.edu

**Comment by andrew-silvernail** [comment]
> The same person from #26 is having issues creating a student account. I think she means that she is trying to create new accounts with already used email addresses, since she has forgotten the passwords. If the following email addresses have accounts tied to them, could you please delete the accounts? Also, if you delete the accounts, will she be able to create fresh accounts with the same email addresses?

Sure.  I've deleted the accounts that exist.  There was no user associated with [Russianflagship@international.ucla.edu](mailto:Russianflagship@international.ucla.edu).  

She should now be able to create fresh accounts with those e-mail addresses.

For this sort of issue in the future, you can access the Django admin to delete users.

> 
> [kresin@ad.ucla.edu](mailto:kresin@ad.ucla.edu)
> [kresin@ucla.edu](mailto:kresin@ucla.edu)
> [Russianflagship@international.ucla.edu](mailto:Russianflagship@international.ucla.edu)
