### ISSUE TITLE
Random spaces added in texts

### ISSUE THREAD

**Issue by verbruggenh** [ereadingtool/ereadingtool#28]
In the first paragraph of text 141 "The Russian Film Market", an extra space is seen on the student side and on the glossing page between Интерфакс and », and between » and the immediately following period. On the text edit page, though, it looks normal, so I can't fix it.

In text 132 "Reasons to Leave", two words have been randomly broken up. The first is учёбу in the first paragraph, which has been broken up into уч ё бу. The second is преподаёт in the second paragraph, which has been broken up into препода ё т. Maybe the issue is with the ё letter, since it is sort of a unique letter in Russian? Again, the problem is only visible on the student side and glossing page.

**Comment by jdelamare** [comment]
data has been cleaned and moved onto the dev server.
