### ISSUE TITLE
"Read again" button not working

### ISSUE THREAD

**Issue by wcomer** [ereadingtool/ereadingtool#285]
"Read again" button does not seem to work.  It took me to: https://steps2ar.org/text/0

When you hover over the "read again" button at the end of a text, no URL shows in the status line.

**Comment by jdelamare** [comment]
Unable to replicate, tried the following:
* Deleting the JWT from local storage (Able to read again but eventually kicked to login page)
* Modifying the JWT before sending (results in 403) not default profile

The `0` profile is reserved for the default user. Although I suspected a JWT timeout, this may not be the case. Further investigation seems warranted.
