### ISSUE TITLE
Editing lemmas on glosses

### ISSUE THREAD

**Issue by wcomer** [ereadingtool/ereadingtool#301]
On the "Translations" tab, if a word appears twice in a text, if you edit the lemma the first time, it doesn't seem to save for the second incarnation of the word.  See attached screen shot.

<img width="1113" alt="STAR Vocab oddity" src="https://user-images.githubusercontent.com/37524445/103581534-0e2d3400-4e91-11eb-831b-98bf1e8c98a1.png">

It's not a problem if each iteration needs to be edited separately, but we'll need to document that fact, and we should probably get rid of the "Save for all" button.

**Comment by jdelamare** [comment]
The expected behavior doesn't seem to happen with other grammemes either. Clicking `Save for all` has no noticeable effect on the word being edited or any other instances of that word. Will need to look more closely at `Save for all`'s purpose.

**Comment by bgins** [comment]
Issue #253 is a related issue that covers the "Save for all" functionality. 

Following up on our discussion:

-  When multiple instances of a word are open, we will show the changes across editing boxes, but we will save changes per word when a content editor presses the save button. Showing the change across fields makes editing faster and more convenient, but intent to save must be explicit. This should be documented.
- If we add "Save for all", it should only save instances of a word that are currently selected for editing.

**Comment by bgins** [comment]
"Save for all" has been fixed, but for now, it saves for all words in the text. Fixed in #351.
