### ISSUE TITLE
Add content creator guide

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#341]
Let's add a guide for content creators with instructions and screenshots. Add a link to the page in the navbar for content creators.

**Comment by bgins** [comment]
A page and some placeholder content for this page are started on `feature/content-creator-guide`.

**Comment by jdelamare** [comment]
There are no screenshots in the Content Creator guide that was merged in on PR #392, but I think we're still good to close this issue. Do you agree?

**Comment by jdelamare** [comment]
Content Creator guide is in!
