### ISSUE TITLE
Hints modal X button permanently closes modal till refresh

### ISSUE THREAD

**Issue by jdelamare** [ereadingtool/ereadingtool#358]
The hints modal has an X in the upper right corner that closes the modal. Currently there is no way to get the hints back except to refresh the page. The welcome banner will toggle on and off depending on the Hints checkbox. Once the modal is closed with the X, it will not reappear when the Hints checkbox is checked after being unchecked. 

It makes sense to an extent to have the hints checkbox selected and the hints removed by the X. But re-toggling the checkbox should make them reappear. 

In the interest of time, I suggest we remove the X exit button so that hint modals will only be shown if the box is checked.

**Comment by bgins** [comment]
My thoughts are that we currently have the correct behavior. The hints should close and go away because the user has indicated that they don't want hints at the moment by clicking the "x". The next time, they will get another chance to use them or turn them off by toggling "Show Hints".

**Comment by jdelamare** [comment]
I complete agree. Closing issue as it's feature, not a bug. My bad :)
