### ISSUE TITLE
Add student guide

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#362]
Let's add an improved version of the student guide to help new students learn how to use the app. We should:

- [x] Move the content on `/acknowledgements` to `/about`
- [x] Add a getting started page at `/guide/getting-started`
- [x] Add additional pages under `/guide` as needed depending on the content
- [x] Add tabbed navigation between the tabs
- [x] Add guide content written by @floydpalmer
- [x] Update the welcome banner on the student profile page with a link to `/guide/getting-started`

Work on the guide is started on `feature/student-guide`.

**Comment by bgins** [comment]
Issue #71 is related, but we have decided to improve the guide instead.

**Comment by jdelamare** [comment]
#401 closes this issue

**Comment by jdelamare** [comment]
#401 closes this issue
