### ISSUE TITLE
Add gzip compression on web server

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#366]
Let's add `gzip` compression on the web server. This will help us to address #40. No work will be needed on the frontend because most browsers know what to do with gzipped content.

**Comment by jdelamare** [comment]
https://www.digitalocean.com/community/tutorials/how-to-improve-website-performance-using-gzip-and-nginx-on-ubuntu-20-04

<img width="749" alt="Screen Shot 2021-03-01 at 4 02 13 PM" src="https://user-images.githubusercontent.com/32110740/109576795-4d4ebe80-7aa9-11eb-82c0-9d0f3c6f29c6.png">

**Comment by jdelamare** [comment]
Compression brought our performance score up from the twenties to 67.

<img width="992" alt="Screen Shot 2021-03-05 at 8 24 47 AM" src="https://user-images.githubusercontent.com/32110740/110155491-8aad9780-7d9a-11eb-8c7e-a164de8c92e4.png">
