### ISSUE TITLE
Rename 'Search texts' to 'Find a text to read'

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#49]
From a user:

'The label “Find a text to read” is called “Search texts” in other places on the site. On the post-reading page (or maybe the last section of a text page), the name of the link to get a new text is different. We should consistently use “Find a text to read”'.

**Comment by bgins** [comment]
The name of this link was changed to "Texts" in the navbar on all authed pages. In addition, a button has been added per #62 on the post-reading page.
