### ISSUE TITLE
Investigate broken styling on the start page

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#50]
From a stakeholder:

'The styling on the start page is weird… at first I could see it and now I’m getting blank pages… I
don’t see the start button any more…There could be more “button” to the word start'

**Comment by bgins** [comment]
Unable to reproduce bug in production or local development. There is more button to the word "Start" following the changes in #44.

**Comment by jdelamare** [comment]
I'm also unable to reproduce the bug.

**Comment by wcomer** [comment]
The styling of the button seems to be okay, but every once in a while (sorry not to be able to pinpoint), I will jump from picking a text to the first section of the text, even for a text I've not previously had down as read or started. When I clicked the previous button, I got the small intro before the start button.

**Comment by jdelamare** [comment]
May have been a broken ws connection, haven't seen it for a bit.
