### ISSUE TITLE
Investigate 'sections incomplete' accuracy

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#55]
From a stakeholder:

'The “Sections complete” for each text does not seem to be correct. Even when I have gotten all
questions correct, it says I have completed zero sections'.

**Comment by bgins** [comment]
To reproduce, read a text and answer all questions correctly. On the text conclusion page, click on "Read Another Text" to return to the text search page. Search for the text you read and successfully completed. You should see something like:

![incomplete-sections](https://user-images.githubusercontent.com/7957636/95341722-7016d700-086b-11eb-8766-3dcc6e398c30.png)

"Sections Complete" reports 0/2 completed sections, but the reading was completed and all questions have been answered correctly. The expectation is that we see 2/2 here instead.

Examining the websocket traffic, it appears that the frontend reports the sections as completed to the server. It sends the following websocket message from the text conclusion page:

```
{"command": "complete", "result": {"num_of_sections": 2, "complete_sections": 2, "section_scores": 2, "possible_section_scores": 2}}
```

Note that `complete_sections` is 2. Let's take a look at how we store and read completed sections on the backend to see if we are missing something.
