### ISSUE TITLE
When adding a word to the glossary, record the lemma form of the word

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#59]
For glossing on the student side, ensure that when a word is added to the student list of words, that the lemma form of the word is used.  Currently the word in its current form is added to the list instead.

**Comment by bgins** [comment]
The `normal_form` of the word is returned from the `pymorphy2` call to parse the word:

https://github.com/ereadingtool/ereadingtool/blob/acc7722d0a14846e1cbbbbe7171b7e40272450f7/text/translations/mixins.py#L111

We currently use the `normal_form` when calling on Yandex for translations:

https://github.com/ereadingtool/ereadingtool/blob/acc7722d0a14846e1cbbbbe7171b7e40272450f7/text/translations/mixins.py#L117

But we do not record the `normal_form` with the `word_data` for a text word. Looks like we have the information when we process words and a way to recover it retroactively.

**Comment by wcomer** [comment]
Yes, looking through the documentation about pymorphy2, the normal_form is the lemma.  It's too bad that we've not been recording them in the database, but better we figure out a way to capture them now.

**Comment by jdelamare** [comment]
We're showing the lemma, it's stored in the `text_textphrase` table, the translation service adds it when the word is first processed, and a Content Editor can edit the lemma in the translations tab of the editor.

#286  #289
