### ISSUE TITLE
Investigate 'start' button not loading a text

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#64]
From a stakeholder:

'I noticed a few instances when the button to

“Start” reading a text did not work. One example is
the text on Anna Politkovskaya (here are a few
others:
https://stepstoadvancedreading.org/text/9/,
https://stepstoadvancedreading.org/text/15/,
https://stepstoadvancedreading.org/text/57/ ).'

**Comment by andrew-silvernail** [comment]
Confirmed these are broken.  Looks like some grouped words are not working as expected.

**Comment by bgins** [comment]
Unable to reproduce this bug in production or local development.

**Comment by jdelamare** [comment]
I am also unable to reproduce.

**Comment by wcomer** [comment]
This seems to have gotten fixed.  Can't get it to happen neither in the production nor the development versions.
Time to retire this one?
