### ISSUE TITLE
Refactor navbar

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#82]
Refactor the authed navbar to include links for:

- Texts (move "Find a text to read" from lower menu)
- Flashcards (move "Practice Flashcards" from lower menu)
- Profile (links to user profile)
- Logout (move from dropdown menu)

Restyle navbar to dark blue from gradient logo with a new logo and link color to match.

**Comment by andrew-silvernail** [comment]
Per conversation with @bgins we will need to update the backend to abstract the menu items better and include an id or something similar to match on rather than the link text.
