### ISSUE TITLE
Dockerize site

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#85]
Dockerize site for deployment to production and development.

**Comment by jdelamare** [comment]
DM for IP address, set the IP to to ereadingtool.com in `/etc/hosts`. Currently hosted on GCP. 

Spin up new Ubuntu 18.04 machine
!(https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04)[Setup Docker] 
!(https://linuxize.com/post/how-to-install-and-use-docker-compose-on-ubuntu-18-04/)[Setup Docker-Compose]

Perhaps do the logout and in Docker group kung fu... 

Use  `gcloud compute scp ...` for the following files:
ereadingtool.com NGINX conf file
database file 
the two Dockerfiles (maybe not they're in the repo?)
the `docker-compose.yml` file 

run `docker-compose up` in the directory with the YAML file. Should be good to go.
