### ISSUE TITLE
Setup development server

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#89]
Setup a development server running off the `devel` branch.

**Comment by jdelamare** [comment]
This is coupled with !(https://github.com/ereadingtool/ereadingtool/projects/1#card-40418396)[the issue for dockerizing the site] and will be progressed once a domain name is obtained this coming Wed morning.

**Comment by jdelamare** [comment]
Currently using [upgrade/staging](https://github.com/ereadingtool/ereadingtool/tree/upgrade/staging) for the dev branch. Just need to get an A record for api.steps2ar.org
