### ISSUE TITLE
Correct Link

### ISSUE THREAD

**Issue by wcomer** [ereadingtool/ereadingtool#93]
On page: https://stepstoadvancedreading.org/profile/student/
The link in the section called "Research Consent" contains text and link on the word here: To read about those projects and to review and sign consent forms, please go here. 
Replace current "please go here" with 
please go to: https://sites.google.com/pdx.edu/star-russian/home

Make the webaddress an active link. Note that there is no final / after home in the address

**Comment by andrew-silvernail** [comment]
Verified working on production.
